--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/CustomSetting
build-by-default: true
branches:
- master
projects:
  CustomSetting:
    path: ""
    icon: "icon.png"
...
